Start-Process "C:\Users\otoni\AppData\Local\Programs\Microsoft VS Code\Code.exe"
Start-Process "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" "https://www.linkedin.com"
Start-Process "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" "https://www.github.com/euotiniel"
Start-Process "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" "https://www.youtube.com"
Start-Process "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" "https://www.instagram.com/euotiniel"
